printWidth = 100
tabWidth = 4
useTabs = false
semi = true
singleQuote = true
quoteProps = 'as-needed'
jsxSingleQuote = false
trailingComma = 'all'
bracketSpacing = true
bracketSameLine = false
arrowParens = 'always'
rangeStart = 0
requirePragma = false
insertPragma = false
proseWrap = 'preserve'
htmlWhitespaceSensitivity = 'css'
vueIndentScriptAndStyle = false
endOfLine = 'lf'
embeddedLanguageFormatting = 'auto'
