// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackupButtons: typeof import('./components/BackupButtons.vue')['default']
    ChannelBackupButton: typeof import('./components/ChannelBackupButton.vue')['default']
    Divider: typeof import('./components/divider.vue')['default']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HyInput: typeof import('./components/HyInput.vue')['default']
    LangButton: typeof import('./components/LangButton.vue')['default']
    MarkdownTooltip: typeof import('./components/MarkdownTooltip.vue')['default']
    MDX: typeof import('./components/MDX.vue')['default']
    PhotoScroll: typeof import('./components/PhotoScroll.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    RecaptchaV2: typeof import('./components/RecaptchaV2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitPrompt: typeof import('./components/SubmitPrompt.vue')['default']
  }
}
