/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackupButtons: typeof import('./components/BackupButtons.vue')['default']
    ChannelBackupButton: typeof import('./components/ChannelBackupButton.vue')['default']
    Divider: typeof import('./components/divider.vue')['default']
    DynamicIcon: typeof import('./components/DynamicIcon.vue')['default']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HyInput: typeof import('./components/HyInput.vue')['default']
    IEpCheck: typeof import('~icons/ep/check')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpLollipop: typeof import('~icons/ep/lollipop')['default']
    IFasBold: typeof import('~icons/fa6-solid/bold')['default']
    IFasCode: typeof import('~icons/fa6-solid/code')['default']
    IFasEyeSlash: typeof import('~icons/fa6-solid/eye-slash')['default']
    IFasGripLinesVertical: typeof import('~icons/fa6-solid/grip-lines-vertical')['default']
    IFasItalic: typeof import('~icons/fa6-solid/italic')['default']
    IFasLink: typeof import('~icons/fa6-solid/link')['default']
    IFasPaperPlane: typeof import('~icons/fa6-solid/paper-plane')['default']
    IFasStrikethrough: typeof import('~icons/fa6-solid/strikethrough')['default']
    IFasXmark: typeof import('~icons/fa6-solid/xmark')['default']
    LangButton: typeof import('./components/LangButton.vue')['default']
    MarkdownTooltip: typeof import('./components/MarkdownTooltip.vue')['default']
    MDX: typeof import('./components/MDX.vue')['default']
    PhotoScroll: typeof import('./components/PhotoScroll.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    RecaptchaV2: typeof import('./components/RecaptchaV2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitPrompt: typeof import('./components/SubmitPrompt.vue')['default']
  }
}
